### ISSUE TITLE
Create a name for the tool

### ISSUE THREAD

**Issue by geerdink** [scala-academy/performance-analysis#28]
We need a cool sounding name for our product!

**Comment by Neojume** [comment]
Gravia? Means Log in Latin. Coincedentally Gravia is also a municipality in Greece, one of its districts being Kastellia.

Otherwise maybe: Periphas. Sounds a bit like PERFormance AnalyticS, capitalization on purpose. A well loved king in Ancient Greece, known for his righteousness. Was transformed into an eagle.. (logo opportunities here :P )

**Comment by effibennekers** [comment]
μετρητής?

**Comment by TimSoethout** [comment]
Whistleblower API It will complain/alert after too much injustice has been done!
Maybe some whistleblower from mythology? -Effi: PAN :)

**Comment by jwvl** [comment]
Apiretic <- apyretic "vrij van koorts"
https://en.wiktionary.org/wiki/apyretic#English

**Comment by geerdink** [comment]
We'll vote next week!

**Comment by ronnybrunswijk** [comment]
How about the 'Penalyser' -> performance analyser that 'penalises' poor performance.

**Comment by TimSoethout** [comment]
And the voting results are:

Gravia 4
Periphas 7
Metritis 2
Whistle Blower (API) 2
Apiretic 4
Penalyser 2

Periphas IT IS!
